name: Build Image

on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest-amd64

    steps:
      - uses: actions/checkout@v3

      - name: Install Buildah
        run: apt-get -y update && apt-get -y install buildah

      - name: Buildah Action
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: weewx
          tags: master
          containerfiles: |
            ./Dockerfile
          extra-args: |
            --storage-driver=vfs
