#!/bin/bash
# Daten beim Deutschen Wetterdienst herunterladen
# Copyright (C) 2021 Johanna Roedenbeck
# licensed under the terms of the General Public Licens (GPL) v3

# Diese Datei ist unter /etc/cron.hourly zu speichern. Sie muss
# ausfuehrbar sein.

export PATH="/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

/usr/local/bin/wget-dwd 2>/dev/null
#/usr/local/bin/dwd-warnings 2>/dev/null >/dev/null

# Soll statt dwd-warnings dwd-cap-warnings verwendet werden,
# hier das Kommentarzeichen entfernen und dafuer eines vor
# die Zeile mit dwd-warnings setzen
/usr/local/bin/dwd-cap-warnings --config=/data/weewx.conf --resolution=city 2>/dev/null >/dev/null

# Fuer Wettervorhersagen XXXXX durch den Stationscode
# ersetzen und das Kommentarzeichen entfernen.
/usr/local/bin/dwd-mosmix --config=/data/weewx.conf --daily --hourly K1174 2>/dev/null >/dev/null

# BBK
/usr/local/bin/bbk-warnings --config=/data/weewx.conf 2>/dev/null >/dev/null

# Radar
/usr/bin/wget -nv -O /home/weewx/skins/weewx-wdc/dwd/radar_nrw.gif https://www.dwd.de/DWD/wetter/radar/radfilm_nrw_akt.gif 2>/dev/null >/dev/null

exit 0
